image: docker:stable

variables:
  # Needed for Docker access in the container.
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  GITLAB_IMAGE_NAME: $CI_REGISTRY/ultimaker/cura/$CI_PROJECT_NAME:$CI_COMMIT_SHA

stages:
  - build

# Builds the Docker image and uploads it to the local registry of GitLab so we can use it later on as base image.
build docker:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $GITLAB_IMAGE_NAME .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $GITLAB_IMAGE_NAME
  only:
    - master
    - optimize-docker-builds
